# ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubetasker-controller-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubetasker-controller
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
    - kubetasker-system
  endpoints:
  - port: metrics
    path: /metrics
    scheme: https
    interval: 15s
    tlsConfig:
      insecureSkipVerify: true
