# Service
apiVersion: v1
kind: Service
metadata:
  name: kubetasker-frontend
  namespace: kubetasker-system
  labels:
    app.kubernetes.io/name: kubetasker-frontend
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: kubetasker-frontend
    app.kubernetes.io/component: frontend
  ports:
  - name: http
    port: 8000
    targetPort: http
  - name: metrics
    port: 8081
    targetPort: metrics
