# ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubetasker-frontend-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubetasker-frontend
      app.kubernetes.io/component: frontend
  namespaceSelector:
    matchNames:
    - kubetasker-system
  endpoints:
  - port: metrics
    path: /metrics
    scheme: http
    interval: 15s
