#
# Development Environment values for kubetasker
#

global:
  imagePullPolicy: IfNotPresent

kubetasker-controller:
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  metrics:
    enabled: true
    name: metrics
    port: 8081

kubetasker-frontend:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  autoscaling:
    enabled: false
  metrics:
    enabled: true
    name: metrics
    port: 8081
